version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bits
      - SPRING_DATASOURCE_USERNAME=winavit
      - SPRING_DATASOURCE_PASSWORD=winavit2020
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=winavit
      - POSTGRES_PASSWORD=winavit2020
      - POSTGRES_DB=bits
